### PR TITLE
[fix] vren build error on windows cause long

### PR DESCRIPTION
**Pull request by zjjMaiMai**
`error LNK2001: unresolved external symbol "public: long * __cdecl at::Tensor::data_ptr<long>(void)const " (??$data_ptr@J@Tensor@at@@QEBAPEAJXZ)`
current vren extend will build error on windows x64 cause long resolves to int (a 32-bit type).
 fix it by change `long` to `int64_t`.

### CODE REVIEW

**Comment by kwea123** [comment]
merged thank you!

**Comment by kwea123** [comment]
Can you also help to look at issue #18 ? My windows compilation still fails so I don't know if it works on windows

**Comment by 3a1b2c3** [comment]
Cannot get bindings to build with CUDA 11.6, anyone managed?
